### ISSUE TITLE
Allow users to customise their domain name

### ISSUE THREAD

**Issue by leovct** [leovct/ons#3]
## Motivation
At the moment, users can only set the owner, the controller and the resolved address as well as the TTL. We should add more text records to the domains to allow users to specify a profile picture, some social networks links, a description, a website URL, a location, etc.

## Tasks
- [ ] Add a new `customData` field of type `CustomData` struct in the `Record` struct
- [ ] Implement a new `CustomData` struct type allowing to specify a profile picture url (ipfs), some social network links (github, twitter, reddit, telegram, discord), an email, a descriptio, some keywords and a location.
- [ ] Implement getters and setters for these new fields.
