### ISSUE TITLE
Build a simple front-end

### ISSUE THREAD

**Issue by leovct** [leovct/ons#5]
## Motivation
Users should be able to register a new domain, display, set and update their domain records.
The UI should be minimalist, simple and professional at the same time.

## Tasks
- [ ] Come up with a design for the front-end
- [ ] Implement the dApp with Nextjs and ether.js
- [ ] Set up continuous deployment with Vercel

**Comment by leovct** [comment]
https://optimism-name-service.vercel.app/
